// Shared recipe-author engine. Stateless w.r.t. global env — all I/O is
// scoped to the run-dir passed in. Both verify-pr-author (sdk mode) and
// the verify-recipe-author skill (stdin mode) call this entry point.

import * as fs from 'node:fs';
import * as path from 'node:path';

import { assertNoDeniedPatterns } from './recipe-deny.ts';
import { lintRecipeSpec } from './lint-invocation.ts';
import {
  RECIPE_RETRY_POLICY,
  categorizeEslintViolations,
  formatRetryMessage,
  type EslintViolationInput,
} from './recipe-retry-policy.ts';

export interface PromptBundle {
  version: 1;
  prNumber: number;
  runId: string;
  outputSpecPath: string;
  force: boolean;
  prompt: string;
  metadata: {
    agentModel: string;
    referenceSpecs: string[];
    triageGlobs: string[];
    generatedAt: string;
  };
}

export type DispatchFn = (input: { prompt: string; retryMessage?: string }) => Promise<string>;

export type RecipeAuthorStatus =
  | 'spec-written'
  | 'collision'
  | 'deny-regex-hit'
  | 'extract-failed'
  | 'lint-failed'
  | 'regex-failed'
  | 'retry-requested';

export interface RecipeAuthorResult {
  status: RecipeAuthorStatus;
  specPath: string;
  attempts: number;
  lint?: 'clean' | 'failed';
  regex?: 'clean' | 'failed';
  deniedPattern?: string;
  retryMessage?: string;
  runId?: string;
  agentModel: string;
  generatedAt: string;
}

export interface RunRecipeAuthorInput {
  bundle: PromptBundle;
  dispatch: DispatchFn;
  runDir: string;
  /** 1 = first attempt; 2 = retry pass (skill stdin handoff). */
  attempt?: 1 | 2;
  /** Allow either 'sdk' or 'stdin' to govern retry-vs-loop semantics. */
  mode?: 'sdk' | 'stdin';
}

const SPEC_FENCE_START = '<<<SPEC_START>>>';
const SPEC_FENCE_END = '<<<SPEC_END>>>';

// Listener-before-goto: every `page.on(...)` listener registration MUST
// occur before any `page.goto(...)` call. We enforce this with two index
// probes rather than a single multi-line regex (clearer failure mode).
function checkListenerBeforeGoto(source: string): { ok: boolean; reason?: string } {
  const gotoIdx = source.search(/page\s*\.\s*goto\s*\(/);
  if (gotoIdx === -1) {
    return { ok: false, reason: 'No `page.goto(...)` call found.' };
  }
  const listenerIdx = source.search(/page\s*\.\s*on\s*\(\s*['"`](pageerror|console)['"`]/);
  if (listenerIdx === -1) {
    return { ok: false, reason: 'No `page.on("pageerror"|"console", ...)` listener found.' };
  }
  if (listenerIdx > gotoIdx) {
    return {
      ok: false,
      reason: 'Listeners must be registered before the first `page.goto(...)` call.',
    };
  }
  return { ok: true };
}

// Attach pattern: both attachments must appear inside a `finally` block.
function checkAttachPattern(source: string): { ok: boolean; reason?: string } {
  const hasFinally = /\bfinally\s*\{/.test(source);
  if (!hasFinally) {
    return { ok: false, reason: 'No `finally {` block found.' };
  }
  const hasPageErrors = /testInfo\s*\.\s*attach\s*\(\s*['"`]pageErrors['"`]/.test(source);
  const hasConsoleErrors = /testInfo\s*\.\s*attach\s*\(\s*['"`]consoleErrors['"`]/.test(source);
  if (!hasPageErrors) {
    return { ok: false, reason: "Missing `testInfo.attach('pageErrors', ...)`." };
  }
  if (!hasConsoleErrors) {
    return { ok: false, reason: "Missing `testInfo.attach('consoleErrors', ...)`." };
  }
  // Cheap structural check: both attaches must appear after the `finally {`.
  const finallyIdx = source.search(/\bfinally\s*\{/);
  const pageAttachIdx = source.search(/testInfo\s*\.\s*attach\s*\(\s*['"`]pageErrors['"`]/);
  const consoleAttachIdx = source.search(/testInfo\s*\.\s*attach\s*\(\s*['"`]consoleErrors['"`]/);
  if (pageAttachIdx < finallyIdx || consoleAttachIdx < finallyIdx) {
    return { ok: false, reason: 'Both attachments must appear inside the `finally` block.' };
  }
  return { ok: true };
}

function extractSpecBody(reply: string): string | null {
  const startIdx = reply.indexOf(SPEC_FENCE_START);
  if (startIdx === -1) return null;
  const endIdx = reply.indexOf(SPEC_FENCE_END, startIdx + SPEC_FENCE_START.length);
  if (endIdx === -1) return null;
  const body = reply.slice(startIdx + SPEC_FENCE_START.length, endIdx);
  return body.replace(/^\s*\n/, '').replace(/\n\s*$/, '\n');
}

function buildProvenanceHeader(bundle: PromptBundle, generatedAt: string): string {
  const refs = bundle.metadata.referenceSpecs.length
    ? bundle.metadata.referenceSpecs.join(', ')
    : '(none)';
  const globs = bundle.metadata.triageGlobs.length
    ? bundle.metadata.triageGlobs.join(', ')
    : '(none)';
  return [
    '/**',
    ` * Generated by the verify-pr-author harness (Lane A v4).`,
    ` * generatedAt: ${generatedAt}`,
    ` * runId: ${bundle.runId}`,
    ` * prNumber: ${bundle.prNumber}`,
    ` * agentModel: ${bundle.metadata.agentModel}`,
    ` * referenceSpecs: ${refs}`,
    ` * triageGlobs: ${globs}`,
    ` *`,
    ` * Local-dev: this file is human-reviewed before execution. Edit freely.`,
    ` * CI single-round: this file is materialised into the runner workspace`,
    ` * and executed without intermediate human review. Deny-regex + scoped`,
    ` * lint are the load-bearing controls (see scripts/verify/SECURITY.md).`,
    ` * Provenance block above is informational only.`,
    ' */',
    '',
  ].join('\n');
}

function violationsFromLint(
  ruleViolations: Array<{ ruleId: string | null; messages: Array<{ message: string }> }>
): EslintViolationInput[] {
  const out: EslintViolationInput[] = [];
  for (const v of ruleViolations) {
    for (const m of v.messages) {
      out.push({ ruleId: v.ruleId ?? '', message: m.message });
    }
  }
  return out;
}

async function writeResultJson(
  runDir: string,
  result: RecipeAuthorResult,
  fileName = 'result.json'
): Promise<void> {
  await fs.promises.mkdir(runDir, { recursive: true });
  await fs.promises.writeFile(
    path.join(runDir, fileName),
    JSON.stringify(result, null, 2) + '\n',
    'utf-8'
  );
}

export async function runRecipeAuthor(input: RunRecipeAuthorInput): Promise<RecipeAuthorResult> {
  const { bundle, dispatch, runDir } = input;
  const attempt: 1 | 2 = input.attempt ?? 1;
  const mode: 'sdk' | 'stdin' = input.mode ?? 'sdk';
  // Pin generatedAt to the bundle's generation timestamp so that the D8
  // provenance header is byte-stable across stdin/sdk invocations of the
  // same bundle (AC-V4-7a parity).
  const generatedAt = bundle.metadata.generatedAt;
  const agentModel = bundle.metadata.agentModel;

  // 1. TOCTOU collision check (D9).
  if (fs.existsSync(bundle.outputSpecPath) && !bundle.force) {
    const result: RecipeAuthorResult = {
      status: 'collision',
      specPath: bundle.outputSpecPath,
      attempts: 0,
      agentModel,
      generatedAt,
    };
    await writeResultJson(runDir, result);
    return result;
  }

  // When invoked with --retry-of (attempt=2), the prior attempt 1 already
  // counted toward the budget; seed the counter so result.json reports the
  // true attempt index (AC-V4-10).
  let attempts = attempt - 1;
  let retryMessageForNext: string | undefined;

  // Inner attempt loop. Up to RECIPE_RETRY_POLICY.maxAttempts iterations.
  while (attempts < RECIPE_RETRY_POLICY.maxAttempts) {
    attempts += 1;

    const reply = await dispatch({
      prompt: bundle.prompt,
      retryMessage: retryMessageForNext,
    });

    const specBody = extractSpecBody(reply);
    if (specBody === null) {
      const result: RecipeAuthorResult = {
        status: 'extract-failed',
        specPath: bundle.outputSpecPath,
        attempts,
        agentModel,
        generatedAt,
      };
      await writeResultJson(runDir, result);
      return result;
    }

    try {
      assertNoDeniedPatterns(specBody);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      const deniedMatch = msg.match(/denied pattern "([^"]+)"/);
      const result: RecipeAuthorResult = {
        status: 'deny-regex-hit',
        specPath: bundle.outputSpecPath,
        attempts,
        deniedPattern: deniedMatch?.[1],
        agentModel,
        generatedAt,
      };
      await writeResultJson(runDir, result);
      return result;
    }

    const header = buildProvenanceHeader(bundle, generatedAt);
    const fullSource = `${header}${specBody}`;
    const candidatePath = path.join(runDir, 'candidate.spec.ts');
    await fs.promises.mkdir(runDir, { recursive: true });
    await fs.promises.writeFile(candidatePath, fullSource, 'utf-8');

    const lintResult = await lintRecipeSpec({ specPath: candidatePath });
    const listenerCheck = checkListenerBeforeGoto(specBody);
    const attachCheck = checkAttachPattern(specBody);
    const regexOk = listenerCheck.ok && attachCheck.ok;
    const lintOk = lintResult.exitCode === 0;

    if (lintOk && regexOk) {
      // D9 re-check: outputSpecPath may have appeared while we were dispatching.
      if (fs.existsSync(bundle.outputSpecPath) && !bundle.force) {
        const result: RecipeAuthorResult = {
          status: 'collision',
          specPath: bundle.outputSpecPath,
          attempts,
          lint: 'clean',
          regex: 'clean',
          agentModel,
          generatedAt,
        };
        await writeResultJson(runDir, result);
        return result;
      }
      await fs.promises.mkdir(path.dirname(bundle.outputSpecPath), { recursive: true });
      await fs.promises.rename(candidatePath, bundle.outputSpecPath);
      const result: RecipeAuthorResult = {
        status: 'spec-written',
        specPath: bundle.outputSpecPath,
        attempts,
        lint: 'clean',
        regex: 'clean',
        agentModel,
        generatedAt,
      };
      await writeResultJson(runDir, result);
      return result;
    }

    // Failure path: build a retry message and decide whether to loop or
    // return for the orchestrator to drive a fresh dispatch.
    const violations = violationsFromLint(lintResult.ruleViolations);
    if (!listenerCheck.ok) {
      violations.push({
        ruleId: 'verify/listener-before-goto',
        message: listenerCheck.reason ?? 'listeners must precede page.goto',
      });
    }
    if (!attachCheck.ok) {
      violations.push({
        ruleId: 'verify/attach-pattern',
        message: attachCheck.reason ?? 'attachments must be inside finally',
      });
    }
    const buckets = categorizeEslintViolations(violations);
    const rawJson = JSON.stringify(lintResult.rawJson ?? lintResult.stdout, null, 2);
    const retryMessage = formatRetryMessage(buckets, rawJson);

    const exhausted = attempts >= RECIPE_RETRY_POLICY.maxAttempts;
    if (exhausted) {
      const result: RecipeAuthorResult = {
        status: lintOk ? 'regex-failed' : 'lint-failed',
        specPath: bundle.outputSpecPath,
        attempts,
        lint: lintOk ? 'clean' : 'failed',
        regex: regexOk ? 'clean' : 'failed',
        retryMessage,
        agentModel,
        generatedAt,
      };
      await writeResultJson(runDir, result);
      return result;
    }

    // First failure with attempts remaining.
    if (mode === 'stdin' && attempt === 1) {
      // Skill mode: the orchestrator runs the second dispatch under
      // human review. We hand the retry-message back through a partial
      // result and exit cleanly so the skill can frame it.
      const partial: RecipeAuthorResult = {
        status: 'retry-requested',
        specPath: bundle.outputSpecPath,
        attempts,
        lint: lintOk ? 'clean' : 'failed',
        regex: regexOk ? 'clean' : 'failed',
        retryMessage,
        runId: bundle.runId,
        agentModel,
        generatedAt,
      };
      await writeResultJson(runDir, partial, 'result.partial.json');
      return partial;
    }

    // SDK mode (or stdin attempt 2 supplied via --retry-of): loop in-process.
    retryMessageForNext = retryMessage;
  }

  // Unreachable: the loop returns on every branch. Defensive return so
  // TypeScript sees a value path.
  const result: RecipeAuthorResult = {
    status: 'lint-failed',
    specPath: bundle.outputSpecPath,
    attempts,
    agentModel,
    generatedAt,
  };
  await writeResultJson(runDir, result);
  return result;
}
